### ISSUE TITLE
AttributeError: 'RACNN' object has no attribute '__echo_apn'

### ISSUE THREAD

**Issue by istar0me** [klrc/RACNN-pytorch#2]
Thanks for making this project, It's convenient for me to implement RACNN in PyTorch.😄
However, When I load a trained model, I found the error below:

```
(pytorch) root@server:~/RACNN-PYTORCH_orchids# python test.py
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    model = torch.load("build/racnn_mobilenetv2_cub200-e40se401635929775.pt")
  File "/home/user/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/serialization.py", line 607, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/user/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/serialization.py", line 882, in _load
    result = unpickler.load()
  File "/home/user/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'RACNN' object has no attribute '__echo_apn'
``` 

After I did some researches, I guess the problem is the typo of these two lines:

https://github.com/klrc/RACNN-pytorch/blob/323780d27ecbc7d99ce3ebec5cd8ae4cc6eabb0a/src/recurrent_attention_network_paper/forge.py#L94-L95

If I replace `model.state_dict` with `model.state_dict()`, the probelm was solved.
Hope you can edit your code, thanks for your hard work!

**Comment by klrc** [comment]
Thanks! thats right, I'll edit it.
